version: '3'
services:
  php:
    image: php:8.1.18-apache
    volumes:
      - ./BabyXpress:/var/www/html
    ports:
      - 7070:80
  
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=dbbabyxpress
      - MYSQL_ROOT_PASSWORD=asdf
    volumes:
      - ./BabyXpress/Controller/dbbabyxpress.sql:/docker-entrypoint-initdb.d/your-mysql-file.sql
